// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzfkyfpnkszgpejfskma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6Zmt5ZnBua3N6Z3BlamZza21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjYwNTgsImV4cCI6MjA2NTUwMjA1OH0.bKItOr49VZ40ejYjaeYpMOHejiJ5_SyVMQDYKDFU7Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);